### ISSUE TITLE
preprocessing.py文件确实

### ISSUE THREAD

**Issue by saltever** [casivi-research/noco-ad#1]
您好，请问cifar10.py里面有一个from.perprocessing import get_target_label_idx,global_contrast_normalization，但是同级目录下没有perprocessing.py？

**Comment by bebop96** [comment]
已更新

**Comment by saltever** [comment]
谢谢您的回复！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月18日 11:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [casivi-research/noco-ad] preprocessing.py文件确实 (Issue #1) |

Closed #1 as completed.
